// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gekyvzylusuxspxuobcw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdla3l2enlsdXN1eHNweHVvYmN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNjQzNzMsImV4cCI6MjA2MTY0MDM3M30.ORfyAFbpbpF4PnC5xcZWuuoHGqZo2GpztburLuO-LUg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);